package htmlreport

var cross = `				<td style="text-align:center;"><svg style="color: red" xmlns="http://www.w3.org/2000/svg"
width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"
	fill="red"></path>
<path
	d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"
	fill="red"></path>
</svg></td>`

var tick = `<td style="text-align:center;"><svg style="color: rgb(32, 217, 8);"
xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
class="bi bi-check-circle" viewBox="0 0 16 16">
<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"
	fill="#20d908"></path>
<path
	d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"
	fill="#20d908"></path>
</svg></td>`

var failReason = `
<tr>
<th>Fail Reason </th>
<td>%s</td>
</tr>`

var tableTemplate = `					<tr>
<td>%s</td>
%s
<td class="expandChildTable">
	<div class="childTableRow">
		<table class="table" id="innerTable">
			<tr>
				<th>Description </th>
				<td>%s</td>
			</tr>
			%s
			<tr>
			<th>Rationale</th>
			<td>%s</td>
		</tr>
		<tr>
		<th>Process to Validate </th>
		<td>%s</td>
	</tr>
	<tr>
	<th>References</th>
	<td>%s</td>
</tr>

			
		</table>
	</div>
</td>
</tr>`

const tabLink = `<li class="nav-item">
<a class="nav-link %s" href="#%s">%s</a>
</li>`

const tabContent = `<div id="%s" class="tab-pane %s">
%s
</div>`

const html = `<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes" />
    <title>Test Report</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
        integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <style>

	.maintable {
		margin: 50px 0;
		padding: 20px;
		box-shadow: -webkit-box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.32);
		-moz-box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.32);
		box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.32);
		width: 100%;
		border-collapse: collapse;
		overflow-x: auto;
	}

	.maintable thead th {
		position: sticky;
		top: 0;
		background-color: white;
		z-index: 10;
	}

	.maintable th tr {
		min-width: 120px;
		border:
	}

	.expandChildTable:before {
		content: "+";
		display: block;
		text-align: center;
		cursor: pointer;
	}

	.expandChildTable.selected:before {
		content: "-";
	}

	.childTableRow {
		display: none;

	}

	#innerTable {
		width: 500px;
		float: right;
	}

	.childTableRow table {
		border: 2px solid #555;
	}

	.table-responsive {
		overflow-x: auto;
	}

	
        /* Header Styles */
        header {
            background-color: #333;
            color: #fff;
            padding: 10px;
        }

        .header-title {
            font-size: 24px;
            font-weight: bold;
			color: #555;
        }

        /* Container Styles */
        .container {
            margin: 20px auto;
            padding: 20px;
            background-color: #f7f7f7;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        /* Tab Styles */
        .nav-link {
            padding: 10px 20px;
            border: none;
            background-color: #f0f0f0;
            color: #333;
            border-radius: 5px 5px 0 0;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .nav-link.active {
            background-color: #fff;
            color: #333;
        }

        .tab-content {
            display: none;
            padding: 20px;
            background-color: #fff;
            border-radius: 0 5px 5px 5px;
        }

        .tab-content.active-tab {
            display: block;
        }
    </style>
</head>

<body>
    <header>
        <div class="container">
            <h1 class="header-title">Test Report</h1>
        </div>
    </header>
    <div class="container">
        <ul class="nav nav-tabs">
            %s
        </ul>
        <div class="tab-content active-tab">
            %s
        </div>
    </div>

	<footer>
		<div class="container">
			Report generated by KloudDB Shield (Klouddb.io)
		</div>
	</footer>

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
        integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <script>
	$(document).ready(function () {
		// Switch active tab and show corresponding content
		$(".nav-link").on("click", function (e) {
			e.preventDefault();
			$(".nav-link").removeClass("active");
			$(this).addClass("active");
			$(".tab-pane").removeClass("active");
			$($(this).attr("href")).addClass("active");
			$(".tab-content").addClass("active-tab");
		});

		// Toggle "selected" class on expandChildTableElement
		$(".expandChildTable").on("click", function () {
			$(this).toggleClass("selected");
			$(this).find(".childTableRow").toggle();
		});
	
		// Show the default active tab
		$(".nav-link.active").trigger("click");
	});	
    </script>

</body>

</html>`

var body = `
	<div class="wrapper">
		<div class="myContainer">
			<div class="table-responsive">

				<table class="table maintable">
					<thead>
						<tr>
							<th>Control</th>
							<th style="text-align:center;">Result</th>
							<th style="width: 540px;text-align:center;">Detailed Status</th>

						</tr>
					</thead>

	%s

				</table>
			</div>
		</div>
		%s
	</div>
	`

var hbatabletemplate = `
<tr>
	<td>%s</td>
	%s
	<td class="expandChildTable">
		<div class="childTableRow">
			<table class="table" id="innerTable">
				<tr>
					<th>Description </th>
					<td>%s</td>
				</tr>
					%s
				<tr>
					<th>Process to Validate </th>
					<td>%s</td>
				</tr>
			</table>
		</div>
	</td>
</tr>`

var hbafailRows = `
<tr>
<th>Failed Rows </th>
<td>%s</td>
</tr>`

// var hbafailReason = `
// <tr>
// <th>Failed Rows </th>
// <td>%s</td>
// </tr>`
var hbaFailRowsBodyTemplate = `
<div class="container">
					<h6>%s</h6>
				</div>
<div class="container">

	<table class="table maintable">
		<thead>
			<tr>
				<th>Line Number</th>
				<th style="text-align:left;">HBA Entry</th>
			</tr>
		</thead>
		%s
	</table>
</div>`
var hbaFailRowsTemplate = `	
	
			<tr>
				<td>%d</td>
		
				<td>%s</td>
			</tr>
		
`
