package htmlreport

var cross = `				<td style="text-align:center;"><svg style="color: red" xmlns="http://www.w3.org/2000/svg"
width="16" height="16" fill="currentColor" class="bi bi-x-circle" viewBox="0 0 16 16">
<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"
	fill="red"></path>
<path
	d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"
	fill="red"></path>
</svg></td>`

var tick = `<td style="text-align:center;"><svg style="color: rgb(32, 217, 8);"
xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
class="bi bi-check-circle" viewBox="0 0 16 16">
<path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"
	fill="#20d908"></path>
<path
	d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"
	fill="#20d908"></path>
</svg></td>`
var failReason = `
<tr>
<th>Fail Reason </th>
<td>%s</td>
</tr>`
var tableTemplate = `					<tr>
<td>%s</td>
%s
<td><span class="expandChildTable"></span>
	<div class="childTableRow">
		<table class="table" id="innerTable">
			<tr>
				<th>Description </th>
				<td>%s</td>
			</tr>
			%s
			<tr>
			<th>Rationale</th>
			<td>%s</td>
		</tr>
		<tr>
		<th>Process to Validate </th>
		<td>%s</td>
	</tr>
	<tr>
	<th>References</th>
	<td>%s</td>
</tr>

			
		</table>
	</div>
</td>
</tr>`

var body = `<!doctype html>
<html>

<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=yes" />
	<title>Test Report</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
		integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

	<style>
		.expandChildTable:before {
			content: "+";
			display: block;
			text-align: center;
			cursor: pointer;
		}

		.expandChildTable.selected:before {
			content: "-";
		}

		.childTableRow {
			display: none;

		}

		#innerTable {
			width: 500px;
			float: right;
		}

		.childTableRow table {
			border: 2px solid #555;
		}

		#maintable {
			margin: 50px 0;
			padding: 20px;
			box-shadow: -webkit-box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.32);
			-moz-box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.32);
			box-shadow: 0px 0px 5px 0px rgba(0, 0, 0, 0.32);
		}
	</style>
</head>

<body>
	<div class="wrapper">
		<div class="myContainer">
			<header>
				<div class="container">
					<h1 class="col-lg-9">%s CIS Report</h1>
				</div>
			</header>
			<div class="container">

				<table class="table" id="maintable">
					<thead>
						<tr>
							<th>Control</th>
							<th style="text-align:center;">Result</th>
							<th style="width: 540px;text-align:center; ">Detailed Status</th>

						</tr>
					</thead>

%s

				</table>
			</div>
		</div>
	</div>
	<footer>
		<div class="container">
			Report generated by KloudDB Shield (Klouddb.io)
		</div>
	</footer>


	<!-- Latest compiled and minified JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
		integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"
		integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
		crossorigin="anonymous"></script><!-- <script src="js/disqus-config.js"></script> -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
	<script>
		$(document).ready(function () {
			$('.expandChildTable').on('click', function () {
				// $(this).toggleClass('selected').closest('div').next().toggle();
				$(this).toggleClass('.childTableRow').next().toggle();
			})
		});
	</script>
</body>

</html>`
