# golangci-lint configuration used for CI
run:
  tests: true
  timeout: 10m

issues:
  exclude-use-default: true
  exclude-case-sensitive: false
  exclude-dirs-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false
  whole-files: false
  exclude-files:
    - ".*\\.pb\\.go"

linters-settings:
  revive:
    ignore-generated-header: false
    severity: warning
    confidence: 0.8
    rules:
      - name: unreachable-code
      - name: errorf
      - name: range
      - name: superfluous-else
      - name: var-declaration

linters:
  disable-all: true
  enable:
    - misspell
    - gofmt
    - staticcheck
    # - gosec
    # - gocritic
    - govet
    - errcheck
    - gosimple
    - govet
    - typecheck
    - gofmt
    - goimports
    - unused
