# golangci-lint v2 config
version: "2"

run:
  tests: true

linters:
  default: none
  enable:
    - misspell
    - staticcheck
    - govet
    - errcheck
    - unused

  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false
  whole-files: false
