# profile-11: gss / krb5 commented legacy entries
# hostgssenc all        all             0.0.0.0/0               gss
host    all             all             10.11.0.0/16            md5
host    all             all             10.11.0.0/16            reject
