# profile-12: role-specific superuser exposure
host    all             user2           0.0.0.0/0               trust
host    all             user3           10.12.0.0/16            trust
host    all             all             10.12.0.0/16            scram-sha-256
