# profile-02: scram-sha-256 only for application users
host    shielddb        shielduser      127.0.0.1/32            scram-sha-256
host    shielddb        shielduser      ::1/128                 scram-sha-256
host    all             all             10.0.0.0/8              scram-sha-256
