# profile-13: staggered CIDR overlaps
host    all             all             10.13.0.0/16            md5
host    all             all             10.13.128.0/17          reject
host    all             all             10.13.64.0/18           scram-sha-256
