# profile-10: ldap-style comment block + trust local subnet
# ldapserver=ldap.example.com
host    all             all             10.10.0.0/16            trust
host    all             all             10.11.0.0/16            md5
host    all             all             10.12.0.0/16            scram-sha-256
