# profile-06: database-scoped rules
host    shielddb        all             192.168.1.0/24          md5
host    postgres        all             192.168.1.0/24          reject
host    template1       all             192.168.1.0/24          reject
host    all             all             10.10.0.0/16            scram-sha-256
