# profile-09: SSL-required local connections + narrow remote allow-list
hostssl shielddb        shielduser      127.0.0.1/32            scram-sha-256
hostssl shielddb        shielduser      ::1/128                 scram-sha-256
host    shielddb        shielduser      10.9.0.0/24             scram-sha-256
host    shielddb        user0           10.9.0.0/24             md5
host    all             all             0.0.0.0/0               reject
