# profile-14: strict default — reject wide, allow localhost scram only
host    all             all             0.0.0.0/0               reject
host    all             all             128.0.0.0/1             reject
host    shielddb        shielduser      127.0.0.1/32            scram-sha-256
host    shielddb        shielduser      ::1/128                 scram-sha-256
