# profile-01: md5 for remote, reject broad ranges
host    all             all             0.0.0.0/0               reject
host    all             all             192.168.0.0/16          md5
host    all             all             10.0.0.0/8              md5
