# profile-04: superuser roles with trust (CIS violation pattern)
host    all             user0           0.0.0.0/0               trust
host    all             user1           0.0.0.0/0               trust
host    all             all             127.0.0.1/32            scram-sha-256
