name: Golang Vulnerability Check
on:
  push:
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
jobs:
  golangci:
    name: Golang Vulnerability Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.11
          cache: true
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-package: ./...
